export const CREATE_LIKE_INIT = 'CREATE_LIKE_INIT'
export const DELETE_LIKE_INIT = 'DELETE_LIKE_INIT'
export const GET_LIKES_COUNT_INIT = 'GET_LIKES_COUNT_INIT'
export const GET_LIKE_STATE_INIT = 'GET_LIKE_STATE_INIT'

export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS'
export const DELETE_LIKE_SUCCESS = 'DELETE_LIKE_SUCCESS'
export const GET_LIKES_COUNT_SUCCESS = 'GET_LIKES_COUNT_SUCCESS'
export const GET_LIKE_STATE_SUCCESS = 'GET_LIKE_STATE_SUCCESS'

export const CREATE_LIKE_FAIL = 'CREATE_LIKE_FAIL'
export const DELETE_LIKE_FAIL = 'DELETE_LIKE_FAIL'
export const GET_LIKES_COUNT_FAIL = 'GET_LIKES_COUNT_FAIL'
export const GET_LIKE_STATE_FAIL = 'GET_LIKE_STATE_FAIL'